* Encoding: UTF-8.
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT UnhealthyFC
  /METHOD=ENTER ParentsHE ParentMotiv_UE
  /METHOD=ENTER centered_ParentMotiv_UE_x_centered_ParentsHE.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT UnhealthyFC
  /METHOD=ENTER PeersHE PeerMotiv_UE
  /METHOD=ENTER centered_PeerMotiv_UE_x_centered_PeersHE.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT UnhealthyFC
  /METHOD=ENTER PartnerHE PartnerMotiv_UE
  /METHOD=ENTER centered_PartnerMotiv_UE_x_centered_PartnerHE.




REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT UnhealthyPA
  /METHOD=ENTER ParentsPA ParentMotiv_noPA
  /METHOD=ENTER centered_ParentMotiv_noPA_x_centered_ParentsPA.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT UnhealthyPA
  /METHOD=ENTER PeersPA PeerMotiv_noPA
  /METHOD=ENTER centered_PeerMotiv_noPA_x_centered_PeersPA.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT UnhealthyPA
  /METHOD=ENTER PartnerPA PartnerMotiv_noPA
  /METHOD=ENTER centered_PartnerMotiv_noPA_x_centered_PartnerPA.




REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT HeavyDrinking
  /METHOD=ENTER ParentsAU ParentMotiv_AU
  /METHOD=ENTER centered_ParentMotiv_AU_x_centered_ParentsAU.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT HeavyDrinking
  /METHOD=ENTER PeersAU PeerMotiv_AU
  /METHOD=ENTER centered_PeerMotiv_AU_x_centered_PeersAU.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT HeavyDrinking
  /METHOD=ENTER PartnerAU PartnerMotiv_AU
  /METHOD=ENTER centered_PartnerMotiv_AU_x_centered_PartnerAU.




REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=ENTER ParentsAU ParentMotiv_AU
  /METHOD=ENTER centered_ParentMotiv_AU_x_centered_ParentsAU.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=ENTER PeersAU PeerMotiv_AU
  /METHOD=ENTER centered_PeerMotiv_AU_x_centered_PeersAU.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=ENTER PartnerAU PartnerMotiv_AU
  /METHOD=ENTER centered_PartnerMotiv_AU_x_centered_PartnerAU.


