* Encoding: UTF-8.
UNIANOVA Diff_UnhealthyFC BY MovedParents WITH Age Ethnicity
  /METHOD=SSTYPE(3)
  /INTERCEPT=INCLUDE
  /EMMEANS=TABLES(MovedParents) WITH(Age=MEAN Ethnicity=MEAN) COMPARE ADJ(BONFERRONI)
  /PRINT ETASQ DESCRIPTIVE
  /CRITERIA=ALPHA(.05)
  /DESIGN=Age Ethnicity MovedParents.

UNIANOVA Diff_UnhealthyFC BY MovedParents WITH Age
  /METHOD=SSTYPE(3)
  /INTERCEPT=INCLUDE
  /EMMEANS=TABLES(MovedParents) WITH(Age=MEAN) COMPARE ADJ(BONFERRONI)
  /PRINT ETASQ DESCRIPTIVE
  /CRITERIA=ALPHA(.05)
  /DESIGN=Age MovedParents.






CORRELATIONS
  /VARIABLES=UnhealthyFC ParentsHE
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_UnhealthyFC ParentsHE
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=UnhealthyFC PartnerHE
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_UnhealthyFC PartnerHE
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=UnhealthyFC PeersHE
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_UnhealthyFC PeersHE
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.






REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT UnhealthyFC
  /METHOD=ENTER ParentsHE Live_w_Parents
  /METHOD=ENTER centered_ParentsHE_x_centered_Live_w_Parents
  /SAVE PRED COOK LEVER SRESID SDRESID.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_UnhealthyFC
  /METHOD=ENTER ParentsHE Live_w_Parents
  /METHOD=ENTER centered_ParentsHE_x_centered_Live_w_Parents
  /SAVE PRED COOK LEVER SRESID SDRESID.







REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT UnhealthyFC
  /METHOD=ENTER ParentsHE ParentMotiv_UE
  /METHOD=ENTER centered_ParentMotiv_UE_x_centered_ParentsHE.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT UnhealthyFC
  /METHOD=ENTER PeersHE PeerMotiv_UE
  /METHOD=ENTER centered_PeerMotiv_UE_x_centered_PeersHE.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT UnhealthyFC
  /METHOD=ENTER PartnerHE PartnerMotiv_UE
  /METHOD=ENTER centered_PartnerMotiv_UE_x_centered_PartnerHE.







REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL CHANGE ZPP
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT UnhealthyFC
  /METHOD=ENTER Age Colombian Ausland
  /METHOD=ENTER PeerTime Live_w_Parents
  /METHOD=ENTER centered_PeerTime_x_Live_w_Parents.




SORT CASES  BY Live_w_Parents.
SPLIT FILE LAYERED BY Live_w_Parents.
REGRESSION
  /DESCRIPTIVES MEAN STDDEV CORR SIG N
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_UnhealthyFC
  /METHOD=ENTER ParentsHE.







