* Encoding: UTF-8.
CORRELATIONS
  /VARIABLES=UnhealthyFC ParentsHE
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_UnhealthyFC ParentsHE
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=UnhealthyPA ParentsPA
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_UnhealthyPA ParentsPA
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=HeavyDrinking ParentsAU
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_HeavyDrinking ParentsAU
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=BingeDrinking ParentsAU
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_BingeDrinking ParentsAU
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

