* Encoding: UTF-8.
CORRELATIONS
  /VARIABLES=UnhealthyFC PartnerHE
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_UnhealthyFC PartnerHE
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=UnhealthyPA PartnerPA
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_UnhealthyPA PartnerPA
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=HeavyDrinking PartnerAU
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_HeavyDrinking PartnerAU
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=BingeDrinking PartnerAU
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_BingeDrinking PartnerAU
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

