* Encoding: UTF-8.
CORRELATIONS
  /VARIABLES=UnhealthyFC PeersHE
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_UnhealthyFC PeersHE
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=UnhealthyPA PeersPA
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_UnhealthyPA PeersPA
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=HeavyDrinking PeersAU
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_HeavyDrinking PeersAU
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=BingeDrinking PeersAU
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

CORRELATIONS
  /VARIABLES=Exp_BingeDrinking PeersAU
  /PRINT=TWOTAIL NOSIG FULL
  /STATISTICS DESCRIPTIVES
  /MISSING=PAIRWISE.

