* Encoding: UTF-8.
SORT CASES  BY Live_w_Partner.
SPLIT FILE LAYERED BY Live_w_Partner.
REGRESSION
  /DESCRIPTIVES MEAN STDDEV CORR SIG N
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT HeavyDrinking
  /METHOD=ENTER PartnerAU.

SORT CASES  BY Live_w_Partner.
SPLIT FILE LAYERED BY Live_w_Partner.
REGRESSION
  /DESCRIPTIVES MEAN STDDEV CORR SIG N
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_HeavyDrinking
  /METHOD=ENTER PartnerAU.

SORT CASES  BY Live_w_Partner.
SPLIT FILE LAYERED BY Live_w_Partner.
REGRESSION
  /DESCRIPTIVES MEAN STDDEV CORR SIG N
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=ENTER PartnerAU.

SORT CASES  BY Live_w_Partner.
SPLIT FILE LAYERED BY Live_w_Partner.
REGRESSION
  /DESCRIPTIVES MEAN STDDEV CORR SIG N
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_BingeDrinking
  /METHOD=ENTER PartnerAU.
