* Encoding: UTF-8.
SORT CASES  BY Live_w_Parents.
SPLIT FILE LAYERED BY Live_w_Parents.
REGRESSION
  /DESCRIPTIVES MEAN STDDEV CORR SIG N
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_UnhealthyFC
  /METHOD=ENTER ParentsHE.

SORT CASES  BY Live_w_Parents.
SPLIT FILE LAYERED BY Live_w_Parents.
REGRESSION
  /DESCRIPTIVES MEAN STDDEV CORR SIG N
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT HeavyDrinking
  /METHOD=ENTER ParentsAU.

SORT CASES  BY Live_w_Parents.
SPLIT FILE LAYERED BY Live_w_Parents.
REGRESSION
  /DESCRIPTIVES MEAN STDDEV CORR SIG N
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=ENTER ParentsAU.

SORT CASES  BY Live_w_Parents.
SPLIT FILE LAYERED BY Live_w_Parents.
REGRESSION
  /DESCRIPTIVES MEAN STDDEV CORR SIG N
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_BingeDrinking
  /METHOD=ENTER ParentsAU.

