* Encoding: UTF-8.
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL CHANGE ZPP
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT UnhealthyFC
  /METHOD=ENTER Age Colombian Ausland
  /METHOD=ENTER PeerTime Live_w_Parents
  /METHOD=ENTER centered_PeerTime_x_Live_w_Parents.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL CHANGE ZPP
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT UnhealthyPA
  /METHOD=ENTER Age Colombian Ausland
  /METHOD=ENTER PeerTime Live_w_Parents
  /METHOD=ENTER centered_PeerTime_x_Live_w_Parents.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL CHANGE ZPP
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT HeavyDrinking
  /METHOD=ENTER Age Colombian Ausland
  /METHOD=ENTER PeerTime Live_w_Parents
  /METHOD=ENTER centered_PeerTime_x_Live_w_Parents.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL CHANGE ZPP
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=ENTER Age Colombian Ausland
  /METHOD=ENTER PeerTime Live_w_Parents
  /METHOD=ENTER centered_PeerTime_x_Live_w_Parents.

