* Encoding: UTF-8.
REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER AvailAU.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER AffordAU.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER ParentMotAU.


REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER ParentAU.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER PeerAU.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER PartnerAU.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER Age.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER MovedOut.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER PartyDays.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER TimeParents.





REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER AvailAU.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER AffordAU.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER ParentMotAU.


REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER ParentAU.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER PeerAU.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER PartnerAU.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER Age.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER MovedOut.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER PartyDays.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT Exp_BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER TimeParents.





REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS CI(95) R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=STEPWISE Cohort
  /METHOD=ENTER AvailAU PeerAU PartyDays.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=ENTER Cohort
  /METHOD=ENTER LiveParents MovedOut TimePeers PeerAU PartyDays AvailAU Age.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT BingeDrinking
  /METHOD=ENTER Cohort
  /METHOD=ENTER LiveParents MovedOut TimePeers PeerAU PartyDays AvailAU Age AffordAU.


